name = "ddg-lean"
version = "0.1.0"
defaultTargets = ["Challenge", "Solution"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.31.0"

[[lean_lib]]
name = "Challenge"

[[lean_lib]]
name = "Solution"

[[lean_lib]]
name = "Audit"

[[lean_lib]]
name = "CotanSolution"

[[lean_lib]]
name = "CotanAudit"

[[lean_lib]]
name = "CotanChallenge"
